packages:
  - "apps/**"
  - "packages/**"

catalogs:
  default:
    bullmq: ^5.67.2
    dotenv: ^17.2.3
    zod: ^4.3.6
    lucide-react: "^0.563.0"
    react: ^19.2.3
    react-dom: ^19.2.3

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver